language: php
php:
- 5.6
addons:
  postgresql: '9.4'
install:
- pecl install PDO_PGSQL
- composer install
env:
  global:
  - APP_ENV=test
  - DB_CONNECTION=pgsql
  - DATABASE_URL=postgres://postgres@localhost:5432/surveys
before_script:
- psql -c 'create database surveys;' -U postgres
- php artisan migrate
