language: php
php:
- 5.6
addons:
  postgresql: '9.4'
install:
- pecl install PDO_PGSQL
- composer install
env:
  global:
  - APP_ENV=testing
  - DB_CONNECTION=pgsql
  - DATABASE_URL_TEST=postgres://postgres:@localhost:5432/surveys_testing
  - secure: Gi3NaRUiPBduO5TTgaK95fbRnjLvlqtX2LtKtd9D6FzKPgiCOZNkV/OFRclH6Geimc3S39yAA6HR3MykBKyg+iCKpEfD1At5hBAv4t8Z0INAOu3g39oCtJLJ0dVdoIxHAuFvboLRxSe+NdQQggj3fTbtuOETV9a1m0sc7STrelpCM3EqJTXXapZ02ljGkIZGB89+9EVmbHqmNnb456SfbfcxdBXx4HOwU+H4vjcUf4ZvGJUf42Z4M2FiF3kS0YS13OtqnB1sa0r+R0KnHgcxlKE7EI30gibSAOR4Etdxux7xgA8pHkym5KnWC9BTphJfbkLgeFypkIwNNn9ewymSjyGCPkGEXqzPBeJa+w9LW7rtSL1Yzq69HYwYgEgJcw1/e6+F0ALWX6IvuEFUTlFHskUNo5fWPcL4lzYnT1TnAJmZz76nhoH0bzPshHdnk5Ft3Wbxt+W2CT3a6yLh+pG+GT0D6YIjFtlA2lF3h+HyjHMfgrWLiaas03ESg0D9tm753rbXTBYVdyDB0rFOwaVCGTp9Mvc9r6R7wByO2qOlqn9WEuepaJ6GDXXhQhZluFXlpiSmK9LAp8qmUSTZPqvlbP3X/mtC4edxSNcxW/alzLOLVubPWWqpfHi0cqRDGlFzIDN2pTPv8ZfrlnSHk+wnZrVIkGXoUkFf3dLCOnIaVg0=
before_script:
- psql -c 'create database surveys_testing;' -U postgres
- php artisan migrate
